Librero/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    #url(r'^$', 'libro.views.home'),
    url(r'^admin/', admin.site.urls),
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^libro/', include('libro.urls')),
]

libro/urls.py
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from . import views

app_name = 'libro'
urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^about/', views.about, name='about'),
    #url(r'^/(?P<pk>[0-9]+)/detail', views.DetailView.as_view(), name='detail'), #Otra forma de mostrar el detalle
    url(r'^(?P<pk>[0-9]+)/detail', views.DetailView.as_view(), name='detail'),
    url(r'^list/', views.ListView.as_view(), name='list'),
    #url(r'^list/', login_required(views.ListView.as_view(template_name='list'))),
]

libro/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime

# Create your models here.

@python_2_unicode_compatible # only if you need to support Python 2
class Libro(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(datetime.datetime.now())

    def __str__(self): return self.nombre

libro/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Libro

# Create your views here.

def home(request):
    usuario = request.user
    context = {'usuario': usuario,}
    return render(request, 'libro/index.html', context)

#@login_required(login_url="/admin/login/")
def welcome(request):
    titulo = 'Aplicación de libros'
    saludo = 'Bienvenidos a la aplicación para la gestión de libros, creada y diseñada desde el Framework Django mediante lenguaje Python. '
    context = {
        'titulo': titulo,
        'saludo': saludo,
        'error_mensaje': "Error en la página",
    }
    return render(request, 'libro/welcome.html', context)

def about(request):
    autor = 'Santiago Rojas Manios'
    context = {
        'autor': autor,
        'error_mensaje': "Error en la página",
    }
    return render(request, 'libro/about.html', context)

@method_decorator(login_required(login_url="/admin/login/"), name='dispatch')
class DetailView(generic.DetailView):
    model = Libro
    template_name = 'libro/detail.html'

@method_decorator(login_required(login_url="/admin/login/"), name='dispatch')
class ListView(generic.ListView):
    #model = Libro
    template_name = 'libro/list.html'
    """
    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        return context """

    def get_queryset(self):
        """Retorna la lista de libros ordenados por el atributo nombre"""
        return Libro.objects.order_by('nombre')

libro/templates/libro/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libro/style.css' %}" />
</head>
<body>
<h3><span class="glyphicon glyphicon-bookmark"></span> Acerca de</h3>
<table>
    <tr>
        <td><strong><p>Aplicación:</p></strong></td>
        <td><p>&nbsp; Esta es una pequeña aplicación para gestionar los libros en un librero.</p></td>
    </tr>
    <tr>
        <td><strong><p>Autor:</p></strong></td>
        <td><p>&nbsp; {{ autor }}</p></td>
    </tr>
</table>
</body>
</html>

libro/templates/libro/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libro/style.css' %}" />
</head>
<body>
    <h3><span class="glyphicon glyphicon-book"></span> Libro</h3>
<table>
    <tr>
        <td><strong><p>Nombre:</p></strong></td>
        <td><p>&nbsp; {{ libro.nombre }}</p></td>
    </tr>
    <tr>
        <td><strong><p>Registrado:</p></strong></td>
        <td><p>&nbsp; {{ libro.fecha_registro }}</p></td>
    </tr>
</table>
</body>
</html>

libro/templates/libro/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libro/style.css' %}" />
</head>
<body>
    <h1>Home</h1>
    <ul class="list-group">
        <a href="{% url 'libro:welcome' %}" class="list-group-item" target="_blank">Welcome</a>
        <a href="{% url 'libro:list' %}" class="list-group-item" target="_blank">The book list</a>
        <a href="{% url 'libro:about' %}" class="list-group-item" target="_blank">About</a>
    </ul>

    <h3>Bienvenid@, </h3>
    <p>{{ usuario.first_name }} {{ usuario.last_name }}</p>
    {% for  grupo in usuario.groups.all %}
        <p>{{ grupo }}</p>
        {% for  permiso in grupo.permissions.all %}
            <p>{{ permiso }}</p>
        {% endfor %}
    {% endfor %}

</body>
</html>

libro/templates/libro/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libro/style.css' %}" />
</head>
<body>
<h3><span class="glyphicon glyphicon-list"></span> Libros</h3>
    <ul class="list-group">
        {% for  libro in object_list %}
                <a href="{% url 'libro:detail' libro.id %}"  class="list-group-item" target="_blank">
                    {{ libro.fecha_registro }} - {{ libro.nombre }}
                </a>
        {% empty %}
            <li class="list-group-item">No hay registro de libros.</li>
        {% endfor %}
    </ul>
</body>
</html>

libro/templates/libro/welcome.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.6-dist/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'libro/style.css' %}" />
</head>
<body>
    <h1>{{ titulo }}</h1>
    <p>{{ saludo }}</p>
</body>
</html>